### ISSUE TITLE
Fails with Next.js (SSR)

### ISSUE THREAD

**Issue by HashirSalam** [verygoodsecurity/vgs-collect-js#29]
## Expected Behavior
Should be able to use it with SSR.

## Current Behavior
The app crashes with the following error:
<img width="808" alt="Screen Shot 2021-09-09 at 1 50 31 PM" src="https://user-images.githubusercontent.com/18401755/132656891-84d5a17d-0748-41e4-9fe1-af99f68f5f93.png">

## Possible Solution
Adding the following check solves the problem:
<img width="611" alt="Screen Shot 2021-09-09 at 1 51 13 PM" src="https://user-images.githubusercontent.com/18401755/132656726-d56f88cf-7d2a-4410-a861-deeca861c32f.png">

## Steps to Reproduce (for bugs)
1.  npm i @vgs/collect-js
2. import { loadVGSCollect } from '@vgs/collect-js';
3. Try to load the component and the app will crash
4.

## Context
Currently, it's unusable with Next.js (SSR)

## Your Environment
Next.js (11.0)
MacOS
Chrome
@vgs/collect-js": "^0.4.0"

**Comment by AnnaKudriasheva** [comment]
@HashirSalam thank you for pointing it out! The fix should be deployed to production soon. The new release is planned for Monday.

**Comment by AnnaKudriasheva** [comment]
@HashirSalam we've released a new version of the package - `0.5.0`. Could you please update and let us know if it works now as expected. Thank you!

**Comment by HashirSalam** [comment]
@AnnaKudriasheva  Yes we tried it with latest version ( 0.5.0). It works fine now, Thanks for the quick response.
